<?php

/**
 * @file
 * Entity Meta Relation module.
 */

declare(strict_types = 1);

use Drupal\Core\Render\Element;
use Masterminds\HTML5\Elements;

/**
 * Implements hook_inline_entity_form_reference_form_alter().
 */
function emr_inline_entity_form_entity_form_alter(&$reference_form, &$form_state) {

  // Hide non desirable fields for entity meta when show in inline entity form.
  if ($reference_form['#entity_type'] == 'entity_meta') {
    $reference_form['status']['#access'] = FALSE;
    $reference_form['created']['#access'] = FALSE;
    $reference_form['revision_log']['#access'] = FALSE;

    // Add a new field value that contains all relevant field keys
    // for elements that can have values.
    $emr_fields = $reference_form['#emr_fields']['#value'] ?? [];
    foreach ($reference_form as $id => $element) {
      if (is_array($element) && !Element::property($id) && Element::isVisibleElement($element)) {
        $emr_fields[] = $id;
      }
    }

    $form_state->set($reference_form['#ief_id'], $emr_fields);
  }
}
