entity_meta_relation.entity_meta_relation_type.*:
  type: config_entity
  label: 'Entity Meta Relation type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
