node.type.*.third_party.emr:
  type: mapping
  label: 'Entity meta settings'
  mapping:
    entity_meta_bundles:
      type: sequence
      label: 'Entity meta bundles'
      sequence:
        type: string
        label: 'Menu machine name'
