<?php

/**
 * @file
 * Entity meta relation node module file.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_node_form_alter().
 */
function emr_node_form_node_form_alter(&$form, FormStateInterface &$form_state) {
  $contentEntity = $form_state->getFormObject()->getEntity();
  $form = \Drupal::service('emr.form_manager')->addFormElements($form, $form_state, $contentEntity);
  $form['actions']['submit']['#submit'][] = '_emr_node_submit';
}

/**
 * Submit function used by emr_node_form_node_form_alter.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function _emr_node_submit(array &$form, FormStateInterface &$form_state) {
  $form = \Drupal::service('emr.form_manager')->submitFormElements($form, $form_state);
}
