<?php

/**
 * @file
 * The entity meta example install file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 */
function entity_meta_example_install() {
  \Drupal::service('emr.installer')->installEntityMetaTypeOnContentEntityType('audio', 'node', ['entity_meta_multi_example_ct']);
  \Drupal::service('emr.installer')->installEntityMetaTypeOnContentEntityType('visual', 'node', ['entity_meta_multi_example_ct']);
}
